CREATE TABLE IF NOT EXISTS common (
    name VARCHAR(255) PRIMARY KEY,
    data JSONB,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);